name: Terraform Apply Workflow

on:
  push:
    branches:
      - main
jobs:
  terraform_setup_dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  
    
    steps:
      - name: check out to repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        id: init
        run: |
          terraform fmt
          terraform validate
          terraform init  
      
      - name: Terraform Plan
        id: plan
        run: terraform plan 

  terraform_apply_dev:
    name: "Apply Terraform for dev"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  
    environment: dev
    needs:
      - terraform_setup_dev

    steps:
      - name: check out to repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply to dev
        run: | 
          terraform init
          terraform apply --auto-approve     