name: Terraform Apply Workflow

on:
  push:
    branches:
      - main
jobs:
  terraform_setup_dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  
    
    steps:
      - name: check out to repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.6

      - name: Terraform Init
        id: init
        run: terraform fmt
          
      - name: Terraform Init
        id: init
        run: terraform validate

      - name: Terraform Init
        id: init
        run:  terraform init --backend-config environments/dev/backend.conf
      
      - name: Terraform Plan
        id: plan
        run: terraform plan --var-file environments/dev/dev.tfvars

  terraform_apply_dev:
    name: "Apply Terraform for dev"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  
    environment: dev
    needs:
      - terraform_setup_dev

    steps:
      - name: check out to repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.6

      - name: Terraform Apply to dev
        run: | 
          terraform init --backend-config environments/dev/backend.conf
          terraform apply --var-file environments/dev/dev.tfvars --auto-approve     