name: Terraform Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize  # This includes updates to an existing PR
      - reopened 
    branches:
      - main

jobs:
  pr:
    name: Pull request
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials Action
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Initialize Terraform
        run: terraform init -backend-config=environments/dev/backend.conf
     
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Plan Terraform changes
        run: terraform plan


      - name: Show Pull Request Comments
        id: show-comments
        run: |
          # Define the GitHub API URL to fetch comments on the pull request
          COMMENTS_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/comments"

          # Fetch comments using curl and store the result in a variable
          COMMENTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $COMMENTS_URL)

          # Display the comments
          echo "$COMMENTS"